name: workflow

on:
    push:
        branches:
            -main
        paths-ignore:
            - "README.md"

permissions:
    id-token: write
    contents: read

jobs:
    integration:
        name: Continuos Integration
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v

            - name: Lint code
              uses: echo "Running unit tests"

build-and-push-ecr-image:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        
        - name: Install Utilities
          run: |
            sudo apt-get update
            sudo apt-get install -y jq unzip
        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
        
        - name: Build, tag, and push image to Amazon ECR
          id: build-image
          env:
            IMAGE_TAG: latest
          run: |
            #BUILD DOCKER CONTAINER
            #PUSH CONTAINER TO ECR
            #AND FINALLY DEPLOY ON ECS
            docker build -t ${{ secrets.AWS_ECR_REPO_URI }}:${IMAGE_TAG} .
            docker push ${{ secrets.AWS_ECR_REPO_URI }}:${IMAGE_TAG}